### ISSUE TITLE
Android: method does not override or implement a method from a supertype @Override

### ISSUE THREAD

**Issue by alyrik** [Expensify/react-native-share-menu#10]
```
.../MainActivity.java:26: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:app:compileDebugJavaWithJavac FAILED
```

I'n using RN 0.34.1.

File MainActivity.java seems to be originally structured in a different way you described it in Readme:

```
package com.androidreact;

import com.facebook.react.ReactActivity;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "AndroidReact";
    }
}
```

**Comment by caiosba** [comment]
Can you please try with RN 0.33 in order for us to check whether this is related to RN 0.34?

How did you generate this `MainActivity` btw?

**Comment by alyrik** [comment]
It builds without error only with RN 0.28.

This activity is generated by RN generator. There are two files:
![screen shot 2016-10-07 at 15 33 53](https://cloud.githubusercontent.com/assets/10388022/19189980/8189189c-8ca3-11e6-905b-3e92c25a8040.png)

The content of the second file is following:

```
package com.androidreact;

import android.app.Application;
import android.util.Log;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage()
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }
}
```

**Comment by caiosba** [comment]
After you generate the app with RN 0.34, are you able to run it (without adding the RNSM module or any module)? If not, seems to be an issue with RN itself, or maybe it requires an Android SDK version different than yours.

**Comment by alyrik** [comment]
Yes, I have working app (RN 34, SDK 23.0.1). Everything works well. Build fails only with RNSM plugged in.

**Comment by caiosba** [comment]
I just released a new version (1.1.5) with a PR ( #9 ) that adds support to RN 0.33. Can you try it please?

**Comment by alyrik** [comment]
The only question: what should I do in MainActivity.java (shown above)?

**Comment by caiosba** [comment]
O copied the contents you sent on an earlier comment and added the additions:

```
package com.androidreact;

import android.app.Application;
import android.util.Log;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;

import com.meedan.ShareMenuPackage;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new ShareMenuPackage()
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }
}
```

**Comment by alyrik** [comment]
Yes, I've added these two lines to MainApplication.java and everything works well now! Thank you very much!
P.S. Works with RN 0.33 but not with RN 0.34 (the problem with dependencies in RNSM as I see).

**Comment by caiosba** [comment]
Cool!

**Comment by SaraChicaD** [comment]
Hi there, I'm getting a similar error on `2.2.1` had to switch back to `2.2.0`:

```
> Task :react-native-share-menu:compileDebugJavaWithJavac FAILED
/Users/.../node_modules/react-native-share-menu/android/src/main/java/com/meedan/ShareMenuPackage.java:20: error: method does not override or implement a method from a supertype
  @Override
  ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-share-menu:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by caiosba** [comment]
Please try now, I removed the optional `@Override` annotation, since that method is not available on all versions.

**Comment by CypherGod2333** [comment]
Stop all workflow and stop ad a Budget
